services:
  web:
    image: patrickjwahl/freeloadr-api
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod

  nginx:
    image: patrickjwahl/freeloadr-proxy
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data_prod: